steps:
  - name: "node"
    entrypoint: "npm"
    args: ["install"]

  - name: "node"
    entrypoint: "npm"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e  # Fail the script if any command fails
        gcloud secrets versions access latest --secret="DB_NAME" > /workspace/DB_NAME &&
        echo "DB_NAME=$(cat /workspace/DB_NAME)" >> .env &&
        gcloud secrets versions access latest --secret="DB_USER" > /workspace/DB_USER &&
        echo "DB_USER=$(cat /workspace/DB_USER)" >> .env &&
        gcloud secrets versions access latest --secret="DB_PASSWORD" > /workspace/DB_PASSWORD &&
        echo "DB_PASSWORD=$(cat /workspace/DB_PASSWORD)" >> .env &&
        gcloud secrets versions access latest --secret="DB_HOST" > /workspace/DB_HOST &&
        echo "DB_HOST=$(cat /workspace/DB_HOST)" >> .env &&
        gcloud secrets versions access latest --secret="DB_DIALECT" > /workspace/DB_DIALECT &&
        echo "DB_DIALECT=$(cat /workspace/DB_DIALECT)" >> .env &&
        gcloud secrets versions access latest --secret="SECRET_KEY" > /workspace/SECRET_KEY &&
        echo "SECRET_KEY=$(cat /workspace/SECRET_KEY)" >> .env &&
        gcloud run deploy

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
