steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "pnpm"]

  - name: "node"
    entrypoint: "pnpm"
    args: ["install"]

  - name: "node"
    entrypoint: "pnpm"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret="DB_NAME" > .env &&
        echo "DB_NAME=$(cat .env)" >> .env &&
        gcloud secrets versions access latest --secret="DB_USER" > .env &&
        echo "DB_USER=$(cat .env)" >> .env &&
        gcloud secrets versions access latest --secret="DB_PASSWORD" > .env &&
        echo "DB_PASSWORD=$(cat .env)" >> .env &&
        gcloud secrets versions access latest --secret="DB_HOST" > .env &&
        echo "DB_HOST=$(cat .env)" >> .env &&
        gcloud secrets versions access latest --secret="DB_DIALECT" > .env &&
        echo "DB_DIALECT=$(cat .env)" >> .env &&
        gcloud secrets versions access latest --secret="SECRET_KEY" > .env &&
        echo "SECRET_KEY=$(cat .env)" >> .env &&
        gcloud run deploy gymbro-back-ts --image gcr.io/$PROJECT_ID/gymbro-back-ts --platform managed --region $REGION --set-env-vars PORT=8080

timeout: "1600s"